services:
  db:
    image: postgres:latest
    container_name: pokedex_db
    environment:
      POSTGRES_DB: pokedex
      POSTGRES_USER: pokedex_user
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/changelog:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - pokedex_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pokedex_user -d pokedex"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  pokedex_network:
    driver: bridge

volumes:
  postgres_data: